steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "src/main/docker/Dockerfile.jvm",
        "-t",
        "gcr.io/$PROJECT_ID/quarkus-demo",
        "-t",
        "gcr.io/$PROJECT_ID/quarkus-demo:$TAG_NAME",
        "--cache-from",
        "gcr.io/$PROJECT_ID/quarkus-demo:latest",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/quarkus-demo"

